### PR TITLE
Fix Issue #99

### PR DESCRIPTION
**Pull request by CoryMcDonald**

### CODE REVIEW

**Comment by PassiveModding** [comment]
-    [pbr::OriginalName("CHARMENDER")] Charmender = 4,
+    [pbr::OriginalName("CHARMENDER")] Charmander = 4,

would you also need to change the ID for OriginalName("CHARMENDER") to CHARMANDER ?

**Comment by CoryMcDonald** [comment]
Hey, you're right. :)

**Comment by Dunajka** [comment]
I have one problem. The bot doesnt transfer pokemons if I have TRANSFER DUPLICAT~ set.

What to do?

**Comment by ramseur** [comment]
are you going to merge this into a release?

**Comment by AnthonyOSX** [comment]
The proto should be modified, not manual fixes.

**Pull request closed without merging**
